### ISSUE TITLE
Cannot import name 'Notification' from 'grafanalib.core'

### ISSUE THREAD

**Issue by So-ham** [weaveworks/grafanalib#327]
I was trying to emulate the frontend.json example in the documentation page of grafanalib to get started with this package but while running the script to produce the json, I faced an import error.<br>

## What you expected to happen?
I expected that a json will be produced which can be imported to Grafana.
## What happened?

Traceback (most recent call last):
  File "c:\pthon\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\pthon\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\dasso\Desktop\ml\env\Scripts\generate-dashboard.exe\__main__.py", line 7, in <module>
  File "c:\users\dasso\desktop\ml\env\lib\site-packages\grafanalib\_gen.py", line 132, in generate_dashboard_script
    run_script(generate_dashboard)
  File "c:\users\dasso\desktop\ml\env\lib\site-packages\grafanalib\_gen.py", line 122, in run_script
    sys.exit(f(sys.argv[1:]))
  File "c:\users\dasso\desktop\ml\env\lib\site-packages\grafanalib\_gen.py", line 109, in generate_dashboard
    dashboard = load_dashboard(opts.dashboard)
  File "c:\users\dasso\desktop\ml\env\lib\site-packages\grafanalib\_gen.py", line 27, in load_dashboard
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\dasso\Desktop\ml\src\experiment_scripts\notebooks\example.dashboard.py", line 1, in <module>
    from grafanalib.core import (
ImportError: cannot import name 'Notification' from 'grafanalib.core' (c:\users\dasso\desktop\ml\env\lib\site-packages\grafanalib\core.py)

## How to reproduce it?

Steps I have taken :
- pip install grafanalib
- Copied the code under "Writing dashboards" section of the docs to a file named "example.dashboard.py"
- generate-dashboard -o frontend.json example.dashboard.py

**Comment by JamesGibo** [comment]
Thanks for your interest in grafanalib and taking the time to raise an issue.
This would be because you are using the example from the docs, which is for the latest version of the library which has not yet been released on PyPi. 
Instead you should be using the stable branch of the docs: https://grafanalib.readthedocs.io/en/stable/getting-started.html

**Comment by JamesGibo** [comment]
@dholbach do you think we need to make stable the version the docs defaults too?

**Comment by JamesGibo** [comment]
I have changed the default branch on the docs to stable
https://grafanalib.readthedocs.io 

I will close this issue for now but @So-ham if you have any other issue please re-open.
