### ISSUE TITLE
Unable able to add multiple alert tags via alertRuleTags

### ISSUE THREAD

**Issue by davidshrive** [weaveworks/grafanalib#382]
I've been unable to create an alert with multiple tags as when using a dict with multiple key/value pairs it fails the validation. Not sure if I'm doing something wrong? Setting a single tag works fine.

**Doesn't work**
```
alertRuleTags=dict(Namespace=k8s_ns, Deployment=deployment_name)
```

**Works**
```
alertRuleTags=dict(Namespace=k8s_ns)
```

## What you expected to happen?
Alert be created with multiple tags.

## What happened?
```
TypeError: ("'alertRuleTags' must be <class 'str'> (got False that is a <class 'bool'>).", Attribute(name='alertRuleTags', default=Factory(factory=<class 'dict'>, takes_self=False), validator=<deep_mapping validator for objects mapping <instance_of validator for type <class 'str'>> to <instance_of validator for type <class 'str'>>>, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=None, converter=None, kw_only=False, inherited=False, on_setattr=None), <class 'str'>, False)
```

## How to reproduce it?
Add Alert object and set alertRuleTags to a dict with multiple key/value pairs.

**Comment by JamesGibo** [comment]
Hi, sorry for the slow reply.

Just tested this and Alert does allow you to create with multiple tags, it looks like in your case one of the variables is a boolean `k8s_ns` or `deployment_name`

```python 
from core import Alert

alert = Alert(
    name='test',
    message='help',
    alertConditions='a=b',
    alertRuleTags=dict(Namespace='k8s_ns', Deployment='deployment_name')
)
print(alert.to_json_data())

alert_incorrect = Alert(
    name='test',
    message='help',
    alertConditions='a=b',
    alertRuleTags=dict(Namespace=False, Deployment='deployment_name')
)
print(alert_incorrect.to_json_data())
```

Output, you can see the first one works the seconds gives your error:
```
{'conditions': 'a=b', 'executionErrorState': 'alerting', 'frequency': '60s', 'handler': 1, 'message': 'help', 'name': 'test', 'noDataState': 'no_data', 'notifications': [], 'for': '5m', 'alertRuleTags': {'Namespace': 'k8s_ns', 'Deployment': 'deployment_name'}}


Traceback (most recent call last):
  File "grafanalib/temp.py", line 11, in <module>
    alert_incorrect = Alert(
  File "<attrs generated init core.Alert>", line 19, in __init__
  File "/Users/jamesg/.pyenv/versions/3.8.3/lib/python3.8/site-packages/attrs-20.3.0-py3.8.egg/attr/validators.py", line 358, in __call__
    self.value_validator(inst, attr, value[key])
  File "/Users/jamesg/.pyenv/versions/3.8.3/lib/python3.8/site-packages/attrs-20.3.0-py3.8.egg/attr/validators.py", line 35, in __call__
    raise TypeError(
TypeError: ("'alertRuleTags' must be <class 'str'> (got False that is a <class 'bool'>).", Attribute(name='alertRuleTags', default=Factory(factory=<class 'dict'>, takes_self=False), validator=<deep_mapping validator for objects mapping <instance_of validator for type <class 'str'>> to <instance_of validator for type <class 'str'>>>, repr=True, eq=True, order=True, hash=None, init=True, metadata=mappingproxy({}), type=None, converter=None, kw_only=False, inherited=False, on_setattr=None), <class 'str'>, False)
```

**Comment by JamesGibo** [comment]
I am going to close this issue now, please re-open if the issue still exists
