### ISSUE TITLE
For AlertGroups command

### ISSUE THREAD

**Issue by viju-martin** [weaveworks/grafanalib#537]
Hi,

I have tried to create an alert rule json using generate-alertgroups command from alerts branch code checkedout. Below mentioned are errors when I tried out each option
1)$ generate-alertgroups -o alerts.json  example.alertgroup.py
usage: generate-alertgroups [-h] ALERT [ALERT ...]
generate-alertgroups: error: unrecognized arguments: -o

2)$ generate-alertgroups example.alertgroup.py
Traceback (most recent call last):
  File "C:\Users\vijmarti\AppData\Local\Programs\Python\Python38\Scripts\generate-alertgroups-script.py", line 33, in <module>
    sys.exit(load_entry_point('grafanalib==0.6.3', 'console_scripts', 'generate-alertgroups')())
  File "C:\Users\vijmarti\AppData\Local\Programs\Python\Python38\lib\site-packages\grafanalib-0.6.3-py3.8.egg\grafanalib\_gen.py", line 156, in generate_alertgroups_script
  File "C:\Users\vijmarti\AppData\Local\Programs\Python\Python38\lib\site-packages\grafanalib-0.6.3-py3.8.egg\grafanalib\_gen.py", line 80, in run_script
  File "C:\Users\vijmarti\AppData\Local\Programs\Python\Python38\lib\site-packages\grafanalib-0.6.3-py3.8.egg\grafanalib\_gen.py", line 123, in generate_alertgroups
  File "C:\Users\vijmarti\AppData\Local\Programs\Python\Python38\lib\site-packages\grafanalib-0.6.3-py3.8.egg\grafanalib\_gen.py", line 95, in write_alertgroups
  File "C:\Users\vijmarti\AppData\Local\Programs\Python\Python38\lib\site-packages\grafanalib-0.6.3-py3.8.egg\grafanalib\_gen.py", line 60, in loader
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\vijmarti\grafana_alerts\grafanalib\grafanalib\tests\examples\example.alertgroup.py", line 4, in <module>
    from grafanalib.core import (
ImportError: cannot import name 'AlertRulev8' from 'grafanalib.core' 

How to solve this issue? With grafanalib 0.6.3, I am not able to create alert rule json.

**Comment by JamesGibo** [comment]
Sorry there appears to be a typo in the docs
https://grafanalib.readthedocs.io/en/main/getting-started.html#generating-alerts

Please try
```
generate-alertgroup -o alerts.json example.alertgroup.py
```

**Comment by JamesGibo** [comment]
fixed in #535
